"""Initial migration

Revision ID: b8fe71a39c7b
Revises: 
Create Date: 2025-12-08 15:02:39.521134+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8fe71a39c7b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('erp_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False, comment='物料编码'),
    sa.Column('category', sa.Enum('PAPER', 'INK', 'AUX', name='materialcategory'), nullable=False, comment='物料分类'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='物料名称'),
    sa.Column('gram_weight', sa.Integer(), nullable=True, comment='克重 g/m²'),
    sa.Column('spec_length', sa.Integer(), nullable=True, comment='纸张长度 mm'),
    sa.Column('spec_width', sa.Integer(), nullable=True, comment='纸张宽度 mm'),
    sa.Column('purchase_unit', sa.String(length=10), nullable=False, comment='采购单位（如：令、吨）'),
    sa.Column('stock_unit', sa.String(length=10), nullable=False, comment="库存单位（统一为'张'）"),
    sa.Column('unit_rate', sa.Numeric(precision=10, scale=4), nullable=False, comment='换算率（如：1令=500张，则为500.0000）'),
    sa.Column('current_stock', sa.Numeric(precision=12, scale=2), nullable=False, comment='当前库存（以stock_unit为准）'),
    sa.Column('cost_price', sa.Numeric(precision=10, scale=2), nullable=False, comment='成本单价（元/张）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_erp_materials_code'), 'erp_materials', ['code'], unique=True)
    op.create_index(op.f('ix_erp_materials_id'), 'erp_materials', ['id'], unique=False)
    op.create_table('erp_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_no', sa.String(length=30), nullable=False, comment='订单编号（格式：SO+YYYYMMDD+001）'),
    sa.Column('customer_name', sa.String(length=100), nullable=False, comment='客户名称'),
    sa.Column('contact_person', sa.String(length=50), nullable=True, comment='联系人'),
    sa.Column('contact_phone', sa.String(length=20), nullable=True, comment='联系电话'),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False, comment='订单总金额'),
    sa.Column('status', sa.Enum('DRAFT', 'CONFIRMED', 'PRODUCTION', 'COMPLETED', name='orderstatus'), nullable=False, comment='订单状态'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_erp_orders_id'), 'erp_orders', ['id'], unique=False)
    op.create_index(op.f('ix_erp_orders_order_no'), 'erp_orders', ['order_no'], unique=True)
    op.create_table('sys_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False, comment='用户名'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='密码哈希'),
    sa.Column('role', sa.Enum('ADMIN', 'SALES', 'OPERATOR', name='userrole'), nullable=False, comment='用户角色'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否激活'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_users_id'), 'sys_users', ['id'], unique=False)
    op.create_index(op.f('ix_sys_users_username'), 'sys_users', ['username'], unique=True)
    op.create_table('erp_order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False, comment='订单ID'),
    sa.Column('product_name', sa.String(length=100), nullable=False, comment='产品名称'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='印数（成品数量）'),
    sa.Column('finished_size_w', sa.Integer(), nullable=False, comment='成品宽度 mm'),
    sa.Column('finished_size_h', sa.Integer(), nullable=False, comment='成品高度 mm'),
    sa.Column('page_count', sa.Integer(), nullable=False, comment='页数（P数）'),
    sa.Column('paper_material_id', sa.Integer(), nullable=False, comment='纸张物料ID'),
    sa.Column('crafts', sa.JSON(), nullable=True, comment='工艺详情JSON'),
    sa.Column('paper_usage', sa.Integer(), nullable=True, comment='纸张消耗数（张）'),
    sa.Column('cut_method', sa.String(length=20), nullable=True, comment='开纸方案（DIRECT/ROTATED）'),
    sa.Column('item_amount', sa.Numeric(precision=12, scale=2), nullable=False, comment='明细金额'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['order_id'], ['erp_orders.id'], ),
    sa.ForeignKeyConstraint(['paper_material_id'], ['erp_materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_erp_order_items_id'), 'erp_order_items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_erp_order_items_id'), table_name='erp_order_items')
    op.drop_table('erp_order_items')
    op.drop_index(op.f('ix_sys_users_username'), table_name='sys_users')
    op.drop_index(op.f('ix_sys_users_id'), table_name='sys_users')
    op.drop_table('sys_users')
    op.drop_index(op.f('ix_erp_orders_order_no'), table_name='erp_orders')
    op.drop_index(op.f('ix_erp_orders_id'), table_name='erp_orders')
    op.drop_table('erp_orders')
    op.drop_index(op.f('ix_erp_materials_id'), table_name='erp_materials')
    op.drop_index(op.f('ix_erp_materials_code'), table_name='erp_materials')
    op.drop_table('erp_materials')
    # ### end Alembic commands ###
