"""add_payment_table

Revision ID: b56b3d71bb69
Revises: 368b63fcfacf
Create Date: 2025-12-23 15:39:19.345643+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b56b3d71bb69'
down_revision: Union[str, None] = '368b63fcfacf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('erp_order_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False, comment='订单ID'),
    sa.Column('payment_no', sa.String(length=30), nullable=False, comment='收款单号（格式：PAY+YYYYMMDD+001）'),
    sa.Column('payment_amount', sa.Numeric(precision=12, scale=2), nullable=False, comment='收款金额'),
    sa.Column('payment_method', sa.Enum('CASH', 'BANK_TRANSFER', 'ALIPAY', 'WECHAT', 'CHECK', 'OTHER', name='paymentmethod'), nullable=False, comment='收款方式'),
    sa.Column('payment_date', sa.DateTime(), nullable=False, comment='收款日期'),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', name='paymentstatus'), nullable=False, comment='收款状态'),
    sa.Column('received_by', sa.String(length=50), nullable=False, comment='收款人'),
    sa.Column('voucher_no', sa.String(length=50), nullable=True, comment='凭证号（银行流水号/支付宝订单号等）'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['order_id'], ['erp_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_erp_order_payments_id'), 'erp_order_payments', ['id'], unique=False)
    op.create_index(op.f('ix_erp_order_payments_order_id'), 'erp_order_payments', ['order_id'], unique=False)
    op.create_index(op.f('ix_erp_order_payments_payment_no'), 'erp_order_payments', ['payment_no'], unique=True)
    # Skipping index renames for existing tables to avoid foreign key constraint issues
    # op.drop_index(op.f('idx_contact_phone'), table_name='erp_customers')
    # op.drop_index(op.f('idx_customer_name'), table_name='erp_customers')
    # op.drop_index(op.f('idx_status'), table_name='erp_customers')
    # op.create_index(op.f('ix_erp_customers_contact_phone'), 'erp_customers', ['contact_phone'], unique=False)
    # op.create_index(op.f('ix_erp_customers_customer_name'), 'erp_customers', ['customer_name'], unique=False)
    # op.create_index(op.f('ix_erp_customers_id'), 'erp_customers', ['id'], unique=False)
    # op.create_index(op.f('ix_erp_customers_status'), 'erp_customers', ['status'], unique=False)
    op.alter_column('erp_orders', 'customer_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='客户ID',
               existing_nullable=True)
    # op.drop_index(op.f('idx_customer_id'), table_name='erp_orders')
    # op.create_index(op.f('ix_erp_orders_customer_id'), 'erp_orders', ['customer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_erp_orders_customer_id'), table_name='erp_orders')
    # op.create_index(op.f('idx_customer_id'), 'erp_orders', ['customer_id'], unique=False)
    op.alter_column('erp_orders', 'customer_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='客户ID',
               existing_nullable=True)
    # op.drop_index(op.f('ix_erp_customers_status'), table_name='erp_customers')
    # op.drop_index(op.f('ix_erp_customers_id'), table_name='erp_customers')
    # op.drop_index(op.f('ix_erp_customers_customer_name'), table_name='erp_customers')
    # op.drop_index(op.f('ix_erp_customers_contact_phone'), table_name='erp_customers')
    # op.create_index(op.f('idx_status'), 'erp_customers', ['status'], unique=False)
    # op.create_index(op.f('idx_customer_name'), 'erp_customers', ['customer_name'], unique=False)
    # op.create_index(op.f('idx_contact_phone'), 'erp_customers', ['contact_phone'], unique=False)
    op.drop_index(op.f('ix_erp_order_payments_payment_no'), table_name='erp_order_payments')
    op.drop_index(op.f('ix_erp_order_payments_order_id'), table_name='erp_order_payments')
    op.drop_index(op.f('ix_erp_order_payments_id'), table_name='erp_order_payments')
    op.drop_table('erp_order_payments')
    # ### end Alembic commands ###
