"""Add production tables

Revision ID: 0b33d5224e29
Revises: b8fe71a39c7b
Create Date: 2025-12-21 16:19:38.223138+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b33d5224e29'
down_revision: Union[str, None] = 'b8fe71a39c7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('erp_production_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('production_no', sa.String(length=30), nullable=False, comment='生产工单号 PO+YYYYMMDD+序号'),
    sa.Column('order_id', sa.Integer(), nullable=False, comment='关联订单ID'),
    sa.Column('plan_start_date', sa.DateTime(), nullable=True, comment='计划开始时间'),
    sa.Column('plan_end_date', sa.DateTime(), nullable=True, comment='计划完成时间'),
    sa.Column('actual_start_date', sa.DateTime(), nullable=True, comment='实际开始时间'),
    sa.Column('actual_end_date', sa.DateTime(), nullable=True, comment='实际完成时间'),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='productionstatus'), nullable=False, comment='生产状态'),
    sa.Column('priority', sa.Integer(), nullable=False, comment='优先级 1-10，数字越小优先级越高'),
    sa.Column('operator_name', sa.String(length=50), nullable=True, comment='操作员姓名'),
    sa.Column('machine_name', sa.String(length=50), nullable=True, comment='设备名称'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['order_id'], ['erp_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_erp_production_orders_id'), 'erp_production_orders', ['id'], unique=False)
    op.create_index(op.f('ix_erp_production_orders_production_no'), 'erp_production_orders', ['production_no'], unique=True)
    op.create_table('erp_production_order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('production_order_id', sa.Integer(), nullable=False, comment='生产工单ID'),
    sa.Column('order_item_id', sa.Integer(), nullable=False, comment='订单明细ID'),
    sa.Column('product_name', sa.String(length=100), nullable=False, comment='产品名称'),
    sa.Column('plan_quantity', sa.Integer(), nullable=False, comment='计划生产数量'),
    sa.Column('completed_quantity', sa.Integer(), nullable=False, comment='已完成数量'),
    sa.Column('rejected_quantity', sa.Integer(), nullable=False, comment='报废数量'),
    sa.Column('finished_size_w', sa.Integer(), nullable=False, comment='成品宽度mm'),
    sa.Column('finished_size_h', sa.Integer(), nullable=False, comment='成品高度mm'),
    sa.Column('page_count', sa.Integer(), nullable=False, comment='页数P数'),
    sa.Column('paper_material_id', sa.Integer(), nullable=False, comment='纸张物料ID'),
    sa.Column('paper_usage', sa.Integer(), nullable=False, comment='纸张消耗数量'),
    sa.Column('cut_method', sa.String(length=20), nullable=False, comment='开纸方案 DIRECT/ROTATED'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['order_item_id'], ['erp_order_items.id'], ),
    sa.ForeignKeyConstraint(['paper_material_id'], ['erp_materials.id'], ),
    sa.ForeignKeyConstraint(['production_order_id'], ['erp_production_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_erp_production_order_items_id'), 'erp_production_order_items', ['id'], unique=False)
    op.create_table('erp_production_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('production_order_id', sa.Integer(), nullable=False, comment='生产工单ID'),
    sa.Column('report_type', sa.String(length=20), nullable=False, comment='报工类型: START(开工)/PROGRESS(进度)/COMPLETE(完工)/REJECT(报废)'),
    sa.Column('completed_quantity', sa.Integer(), nullable=False, comment='本次完成数量'),
    sa.Column('rejected_quantity', sa.Integer(), nullable=False, comment='本次报废数量'),
    sa.Column('operator_name', sa.String(length=50), nullable=False, comment='操作员姓名'),
    sa.Column('operator_id', sa.Integer(), nullable=True, comment='操作员用户ID'),
    sa.Column('remark', sa.Text(), nullable=True, comment='报工说明'),
    sa.Column('report_time', sa.DateTime(), nullable=False, comment='报工时间'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['operator_id'], ['sys_users.id'], ),
    sa.ForeignKeyConstraint(['production_order_id'], ['erp_production_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_erp_production_reports_id'), 'erp_production_reports', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_erp_production_reports_id'), table_name='erp_production_reports')
    op.drop_table('erp_production_reports')
    op.drop_index(op.f('ix_erp_production_order_items_id'), table_name='erp_production_order_items')
    op.drop_table('erp_production_order_items')
    op.drop_index(op.f('ix_erp_production_orders_production_no'), table_name='erp_production_orders')
    op.drop_index(op.f('ix_erp_production_orders_id'), table_name='erp_production_orders')
    op.drop_table('erp_production_orders')
    # ### end Alembic commands ###
