"""add stock warning and stock records

Revision ID: cce171d32748
Revises: b56b3d71bb69
Create Date: 2025-12-26 16:28:03.333724+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cce171d32748'
down_revision: Union[str, None] = 'b56b3d71bb69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('erp_stock_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False, comment='物料ID'),
    sa.Column('operation_type', sa.Enum('IN', 'OUT', 'ADJUST', 'RETURN', 'SCRAP', name='stockoperationtype'), nullable=False, comment='操作类型'),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False, comment='变动数量（正数=入库，负数=出库）'),
    sa.Column('unit', sa.String(length=10), nullable=False, comment='操作单位（如：令、吨、张）'),
    sa.Column('before_stock', sa.Numeric(precision=12, scale=2), nullable=False, comment='操作前库存（张）'),
    sa.Column('after_stock', sa.Numeric(precision=12, scale=2), nullable=False, comment='操作后库存（张）'),
    sa.Column('order_id', sa.Integer(), nullable=True, comment='关联订单ID'),
    sa.Column('operator_id', sa.Integer(), nullable=True, comment='操作人ID'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注说明'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['material_id'], ['erp_materials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_erp_stock_records_id'), 'erp_stock_records', ['id'], unique=False)
    op.create_index(op.f('ix_erp_stock_records_material_id'), 'erp_stock_records', ['material_id'], unique=False)
    op.add_column('erp_materials', sa.Column('min_stock', sa.Numeric(precision=12, scale=2), nullable=False, comment='最低库存预警值（张）'))
    op.add_column('erp_materials', sa.Column('safety_stock', sa.Numeric(precision=12, scale=2), nullable=False, comment='安全库存值（张）'))
    # 注释掉：与库存预警无关的索引操作
    # op.drop_index(op.f('idx_customer_id'), table_name='erp_orders')
    # op.create_index(op.f('ix_erp_orders_customer_id'), 'erp_orders', ['customer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 注释掉：与库存预警无关的索引操作
    # op.drop_index(op.f('ix_erp_orders_customer_id'), table_name='erp_orders')
    # op.create_index(op.f('idx_customer_id'), 'erp_orders', ['customer_id'], unique=False)
    op.drop_column('erp_materials', 'safety_stock')
    op.drop_column('erp_materials', 'min_stock')
    op.drop_index(op.f('ix_erp_stock_records_material_id'), table_name='erp_stock_records')
    op.drop_index(op.f('ix_erp_stock_records_id'), table_name='erp_stock_records')
    op.drop_table('erp_stock_records')
    # ### end Alembic commands ###
